# 服务端口号
server:
  port: 8001

# 数据库地址
datasource:
  url: localhost:3306/microservice01

spring:
  application:
    name: microservice-order # 对外暴露的服务名称

  datasource: # 数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000

mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.itcodai.springcloud.entity
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范

# 客户端注册进eureka服务列表里
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/,http://eureka03:7003/eureka/,
    healthcheck:
      enabled: true
  instance:
    instance-id: 订单服务-8001-Hystrix  # 人性化显示出服务的信息（带hystrix）
    prefer-ip-address: true    # 访问路径可显示ip地址
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

# 使用actuator来展示项目的基本信息
info:
  author.name: Mr.
  app.name: microservice
  server.port: ${server.port}
  application.name: ${spring.application.name}

# 配置hystrix dashboard的url访问
# 开启指标流端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


