server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka01:7001/eureka/,http://eureka02:7002/eureka/,http://eureka03:7003/eureka/

  instance:
    instance-id: 消费方服务-9001  # 人性化显示出服务的信息
    prefer-ip-address: true    # 访问路径可显示ip地址
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  application:
    name: order-feign-client


# feign和ribbon结合，指定策略。feign默认的是轮询的策略，这里的配置可以自定义
MICROSERVICE-ORDER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 开启熔断
feign:
  hystrix:
    enabled: true